### ISSUE TITLE
Manually set the folder path for generated components.

### ISSUE THREAD

**Issue by Nishchit14** [albatrosary/generator-angular-eggs#51]
Please provide the manual folder path in config for custom location to store generated files.

Thank you

**Comment by albatrosary** [comment]
All right, we will develop.

Thanks

**Comment by albatrosary** [comment]
Directory structure is as follows. Part of that can be changed 'customize'.
For example, in the case of `hoge` component:

```bash
yo angular-eggs:components hoge
app/[customize]/hoge.html
app/[customize]/hoge.js
test/[customize]/hoge.js
```

**Comment by Nishchit14** [comment]
@albatrosary  Thank you :+1:
