### ISSUE TITLE
Grunt build : multiple issues 

### ISSUE THREAD

**Issue by WAQuentinOrdener** [albatrosary/generator-angular-eggs#59]
A bit unexperienced to task run but I have some issues after bulding my app :

First : fonts folder isn't created I have to manually import him after build

(plus I bower installed and saved components-font-awesome and declared him but I don't really know how to declare path to copy fonts folder in order to point at him after build : I can just copy/paste all the font-awesome files in fonts folder I created).

Second : Images are renamed and my components can no longer point at them after build, have to manualy rename them to initial name.

Third : It seems that Bootstrap v4 generate some issues (first in development popovers.js and after all the plugins seems to crash since they are minified)

Can you tell me what who you like me to link copy in order to help you (and me) fix this please.

Regards.

**Comment by WAQuentinOrdener** [comment]
I resolved 3rd part : your generated index.html have the bootstrap modules bad charged popover.js need tooltip.js to be charged before otherwise after build all the generated plugin crashes.

For the moment I had to desactivate image minification due to bah resolve path in my components after build.

For the second part I moved my fonts folder in styles folder and copy paste font-awesome fonts in order to work the build correctly.

**Comment by albatrosary** [comment]
Hi @WAQuentinOrdener

I am sorry I contacted you late.
I did not go to a vacation :-) .

The folder is targeted for build only for the specified folder.

The reason for using bootstrap 4 has an experimental meaning. There may be cases where it certainly does not work. I have not updated recently so I will do maintenance.

Thanks!

**Comment by WAQuentinOrdener** [comment]
No problem :) really appreciate your work and I gained some competences myself with these obstacles.

I close the subject, hope it will serve others with this experimental bootstrap.
